Models/ErrorViewModel.cs
using System;

namespace JokesApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Joke.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JokesApp.Models
{
    public class Joke //Clase pricipal
    {
        public int id { get; set; }//propiedades de la clase (Atributos con accesador y mutador)
        public string jokeQuestion { get; set; }//shorcut: prop + tab + tab
        public string jokeAnswer { get; set; }

        //shorcut: ctor + tab + tab
        public Joke()//constructor vacio
        {
                
        }
    }
}

Controllers/HomeController.cs
using JokesApp.Models;
using Microsoft.AspNetCore.Authorization;//dependencia de autenticacion [Authorize]
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace JokesApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize]//visible solo para registrados
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/JokesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JokesApp.Data;
using JokesApp.Models;
using Microsoft.AspNetCore.Authorization;

namespace JokesApp.Controllers
{
    public class JokesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public JokesController(ApplicationDbContext context)
        {
            _context = context;
        }

        
        // GET: Jokes
        public async Task<IActionResult> Index()//Index muestra todos los objetos creados
        {
            return View(await _context.Joke.ToListAsync());
        }

        // GET: Jokes/ BuscarBroma
        public async Task<IActionResult> BuscarBroma()
        {
            return View();
        }


        // POST: Jokes/ Resultados de la Busqueda
        public async Task<IActionResult> ResultadoDeBusqueda(String PalabraBuscada) //Se pasa como parametro la palabra buscada
        {
            //String ResultadoDeBusqueda
            //  return "Buscaste la palabra "+ PalabraBuscada; (Se pasa al metodo a string para comprobar el funcionamiento)
            return View("Index", await _context.Joke.Where( b => b.jokeQuestion.Contains(PalabraBuscada)).ToListAsync());
            //Funcion flecha que retorna el index filtrado por la palabra que se ingreso 
        }

        // GET: Jokes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var joke = await _context.Joke
                .FirstOrDefaultAsync(m => m.id == id);
            if (joke == null)
            {
                return NotFound();
            }

            return View(joke);
        }

        [Authorize]
        // GET: Jokes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Jokes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,jokeQuestion,jokeAnswer")] Joke joke)
        {
            if (ModelState.IsValid)
            {
                _context.Add(joke);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(joke);
        }

        [Authorize]
        // GET: Jokes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var joke = await _context.Joke.FindAsync(id);
            if (joke == null)
            {
                return NotFound();
            }
            return View(joke);
        }

        // POST: Jokes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,jokeQuestion,jokeAnswer")] Joke joke)
        {
            if (id != joke.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(joke);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JokeExists(joke.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(joke);
        }

        [Authorize]
        // GET: Jokes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var joke = await _context.Joke
                .FirstOrDefaultAsync(m => m.id == id);
            if (joke == null)
            {
                return NotFound();
            }

            return View(joke);
        }

        [Authorize]
        // POST: Jokes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var joke = await _context.Joke.FindAsync(id);
            _context.Joke.Remove(joke);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool JokeExists(int id)
        {
            return _context.Joke.Any(e => e.id == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bienvenido a la mejor pagina de chistes malos</h1>
    <p>Crea, modifica y elimina chistes! 🤡</p>

   
</div>

Views/Jokes/BuscarBroma.cshtml
<h2>Buscador de bromas</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ResultadoDeBusqueda">

            <div class="form-group">
                <label for="PalabraBuscada" class="control-label"></label>
                <input name="PalabraBuscada" class="form-control" placeholder="Ingresar palabras de la broma" />
            </div>
            <div class="form-group">
                <input type="submit" value="Buscar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Ver todos los chistes</a>
</div>

Views/Jokes/Create.cshtml
@model JokesApp.Models.Joke

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Joke</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="jokeQuestion" class="control-label"></label>
                <input asp-for="jokeQuestion" class="form-control" />
                <span asp-validation-for="jokeQuestion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="jokeAnswer" class="control-label"></label>
                <input asp-for="jokeAnswer" class="form-control" />
                <span asp-validation-for="jokeAnswer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Jokes/Delete.cshtml
@model JokesApp.Models.Joke

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Joke</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.jokeQuestion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.jokeQuestion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.jokeAnswer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.jokeAnswer)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Jokes/Details.cshtml
@model JokesApp.Models.Joke

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles de la broma</h1>

<div>
    <h4>Chiste</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Pregunta
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.jokeQuestion)
        </dd>
        <dt class="col-sm-2">
            <!--Html.DisplayNameFor(model => model.jokeAnswer) display name es texto, Displayfor muestra el string del modelo-->
            Respuesta
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.jokeAnswer)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.id">Editar chiste</a> |
    <a asp-action="Index">Volver atras</a>
</div>

Views/Jokes/Edit.cshtml
@model JokesApp.Models.Joke

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Joke</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="jokeQuestion" class="control-label"></label>
                <input asp-for="jokeQuestion" class="form-control" />
                <span asp-validation-for="jokeQuestion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="jokeAnswer" class="control-label"></label>
                <input asp-for="jokeAnswer" class="form-control" />
                <span asp-validation-for="jokeAnswer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Jokes/Index.cshtml
@model IEnumerable<JokesApp.Models.Joke>

@{
    ViewData["Title"] = "Index";
}

<h1>Ingreso de bromas 😁</h1>

<p>
    <a asp-action="Create">Ingresar nueva broma ✏</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Pregunta
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.jokeQuestion)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Editar broma</a> |
                <a asp-action="Details" asp-route-id="@item.id">Detalles</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JokesApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-warning border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">🤡 </a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">privacidad</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jokes" asp-action="Index">Bromas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jokes" asp-action="BuscarBroma">Buscar 🔍</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-warning">
        <div class="container">
            &copy; 2021 - JokesApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">privacidad</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>